mbedtls: remove static keyword from certain function pointers
zephyrproject-rtos/mbedtls pull request #32
Opened 2021-11-02 17:36 UTC by SebastianBoe

TF-M usually downloads mbedtls and then applies a handful of
patches. These patches were forgotten when Zephyr started to use it's
own mbedtls fork with TF-M.

One of these patches has now been re-applied in this commit. It is
needed for an important code sharing optimization documented in a link
below.

The static keyword is removed from three function pointer
declarations. Aside from allowing the optimization described below
this could theoretically backfire.

There could be other non-static symbols that now trigger aliasing
issues.

The compiler could have trouble optimizing now that it doesn't know of
all symbol usages.

But I believe that in practice this will be OK.

I don't know if there are any plans to upstream this patch to mbedtls
itself.

https://tf-m-user-guide.trustedfirmware.org/docs/technical_references/design_docs/code_sharing.html

Original patch:
https://git.trustedfirmware.org/TF-M/trusted-firmware-m.git/commit/lib/ext/mbedcrypto?id=4a5cc9776ed3b053bac57326931f936fbbc660e9

Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>

Notes:
* Pull requests cannot be accepted until the PR follows the [contributing guidelines](../CONTRIBUTING.md). In particular, each commit must have at least one `Signed-off-by:` line from the committer to certify that the contribution is made under the terms of the [Developer Certificate of Origin](../dco.txt).
* This is just a template, so feel free to use/remove the unnecessary things
## Description
A few sentences describing the overall goals of the pull request's commits.

## Status
**READY/IN DEVELOPMENT/HOLD**

## Requires Backporting
When there is a bug fix, it should be backported to all maintained and supported branches.
Changes do not have to be backported if:
- This PR is a new feature\enhancement
- This PR contains changes in the API. If this is true, and there is a need for the fix to be backported, the fix should be handled differently in the legacy branch

Yes | NO  
Which branch?

## Migrations
If there is any API change, what's the incentive and logic for it.

YES | NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

2021-11-02 17:37 UTC, SebastianBoe commented
@d3zd3z : This PR sends the patch to the zephyr branch, the previous PR incorrectly applied changes to the master branch.

https://github.com/zephyrproject-rtos/mbedtls/pull/28#issuecomment-957974273

2021-11-03 22:39 UTC, d3zd3z requested changes
How difficult would it be to use the commit text, and authorship of the patch we want to apply? You can add [text] tags by the SoB to indicate where you got it from.

2021-11-04 08:11 UTC, SebastianBoe commented
SoB?

2021-11-05 18:56 UTC, d3zd3z commented
Signed-off-by

2021-11-08 11:15 UTC, SebastianBoe commented
It's possible, but there is next-to-none context there, compared to the detailed information in the current git commit message.

So I would prefer to keep the git commit message as-is.

The original git commit message is:

```
+Subject: [PATCH] Enable crypto code sharing between independent binaries
+
+Signed-off-by: Tamas Ban <tamas.ban@arm.com>

```

2021-11-08 23:41 UTC, d3zd3z commented
Although this isn't a significant amount of code, you really should include the Signed-off-by line from Tamas, and I'd credit him as the author of the original patch. Again, it really isn't as important, since it is just commenting out three lines.

2021-11-09 08:23 UTC, SebastianBoe commented
Added SoB and changed the author.

Not sure I agree about changing the author, as the original patch is linked to from commit message, but let's just finish this and move on.

2021-11-15 10:25 UTC, SebastianBoe commented
@d3zd3z : Review has been addressed

2021-11-17 17:26 UTC, d3zd3z approved these changes

2021-11-17 17:26 UTC, merged