Zephyr 3.4.0
zephyrproject-rtos/mbedtls pull request #44
Opened 2023-07-10 23:19 UTC by d3zd3z

Merge upstream 3.4.0.

2023-07-17 22:42 UTC, microbuilder approved these changes

2023-07-18 16:44 UTC, ceolin approved these changes

2023-07-20 11:31 UTC, joerchan requested changes
Something suspicious in the history.

* 3816bcf50 Revert "Move the implication of MBEDTLS_PSA_CRYPTO_CLIENT where it belongs"
* 0a5aaa1b0 Revert "Move the implication of MBEDTLS_PSA_CRYPTO_CLIENT where it belongs"


Why is there 2 reverts of the same commit with different contents?

2023-07-21 12:00 UTC, joerchan approved these changes

2023-07-21 14:00 UTC, merged