bump MbedTLS to 3.6.0
zephyrproject-rtos/mbedtls pull request #53
Opened 2024-04-04 13:55 UTC by tomi-font

https://github.com/Mbed-TLS/mbedtls/releases/tag/v3.6.0

I reapplied the patches applied in https://github.com/zephyrproject-rtos/mbedtls/pull/52 after merging 3.6.0, but
- TF-M patches (https://github.com/TrustedFirmware-M/trusted-firmware-m/tree/main/lib/ext/mbedcrypto) 0001, 0004 and 0006 conflicted. I resolved the conflicts as I thought made sense, effectively keeping the same intended changes, but some of the patches may need to be updated differently or even removed (e.g. 0004 has possibly become obsolete because of the changes in MbedTLS 3.6.0). @antoniode
- I skipped https://github.com/zephyrproject-rtos/mbedtls/pull/52/commits/dd4e81454f4429b01f6bf86ac8d886808f7ec2e8 and https://github.com/zephyrproject-rtos/mbedtls/pull/52/commits/7d7a2d68049c5723a33b41a1c29fcbb09018c6a3 because they seem to have been addressed upstream.

2024-04-05 08:23 UTC, adeaarm commented
I will shortly make patches 0001 to 0006 on top of Mbed TLS 3.6.0 available on review.trustedfirmware.org so you can directly cherry-pick those. I will post here when the change is ready to be picked up.

2024-04-19 06:16 UTC, frkv approved these changes
LGTM

2024-04-19 08:49 UTC, mswarowsky approved these changes
One small NIT but lese lgtm

2024-04-19 08:49 UTC, mswarowsky commented on CMakeLists.txt
> -
To make our future life during updates easier you could add to the commit message that this commit reverts some of the work of the commits:
469f7811fac98617e544aac2b1b2db56040c95db 
and 
f9bbe0de4c97ca532d052106bb471756e55742ae

Or even just add revert commits of these to commits

2024-04-19 17:42 UTC, ceolin requested changes
@tomi-font It seems good. Can you sign off the your commits ? They are misssing

2024-04-24 04:54 UTC, ceolin approved these changes

2024-04-24 04:54 UTC, ceolin commented
Thanks @tomi-font !

2024-04-24 16:49 UTC, d3zd3z approved these changes
Presumably, this is just the reverts, the merge, and necessary changes.

2024-04-26 18:30 UTC, merged