fix: add module name
zephyrproject-rtos/mbedtls pull request #54
Opened 2024-04-17 12:08 UTC by Jappie3

This MR adds the module name in zephyr/module.yml, as is stated in the [official documentation](https://docs.zephyrproject.org/latest/develop/modules.html#module-name):

> Each Zephyr module is given a name by which it can be referred to in the build system.
> The name should be specified in the zephyr/module.yml file. This will ensure the module name is not changeable through user-defined directory names or west manifest files.

2024-04-17 12:34 UTC, ithinuel approved these changes

2025-02-13 06:45 UTC, kartben approved these changes

2025-02-13 07:27 UTC, tomi-font requested changes
Thanks for the fix. There should be a single commit and no merge commits as part of normal PRs (so basically the second commit shouldn't be there).

2025-02-13 17:58 UTC, Jappie3 commented
done

2025-02-14 07:47 UTC, tomi-font requested changes
Please add some of the PR description to the commit message for context. Also, the commit title should rather follow the structure `<area touched>: <what is done>` so e.g. `zephyr/module.yml: add module name`

2025-02-14 14:38 UTC, Jappie3 commented
something like this?

2025-02-14 15:24 UTC, tomi-font approved these changes
Yes!

2025-08-28 14:59 UTC, merged